name: Tests

on:

  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:

  browsers:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Use latest ESR version of Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest-esr

      - run: npm ci
      - run: npm install grunt-cli -g
      - run: grunt ci
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: build/coverage/lcov/lcov.info
